### ISSUE TITLE
GetRolesForUser API

### ISSUE THREAD

**Issue by ErikQQY** [casbin4d/Casbin4D#10]
Is there GetRolesForUser API in Casbin4D?  
I noticed there is GetRolesForUser API missing in Casbin website **Get Started** docs with Delphi example.

[![gwyHsI.png](https://z3.ax1x.com/2021/05/12/gwyHsI.png)](https://imgtu.com/i/gwyHsI)

**Comment by hsluoyz** [comment]
@ErikQQY plz make a PR to remove `Delphi` tab in the docs.

**Comment by jkour** [comment]
Hi @ErikQQY ,

InPolicyManager, there is a method called rolesForEntity. Is this what you are looking for?

See the full documentation here: http://casbin4d.kouraklis.com

**Comment by ErikQQY** [comment]
@jkour I think it is rolesForEntity, I will add it to the docs.

**Comment by ErikQQY** [comment]
@hsluoyz Since I am migrating the docs, I will directly add this API in the migration.

**Comment by hsluoyz** [comment]
@ErikQQY docs v1 still has updates these days. Make sure you know this.

**Comment by ErikQQY** [comment]
OK, I got this :)

**Comment by hsluoyz** [comment]
@ErikQQY so I suggest you putting it to V1 docs. Because it still needs quite a while to wait V2 site ready.

**Comment by ErikQQY** [comment]
Fix this issue in [#215](https://github.com/casbin/casbin-website/pull/215), plz review @hsluoyz.
