### ISSUE TITLE
Both console and VCL demo doesn't work as expected

### ISSUE THREAD

**Issue by ccy** [casbin4d/Casbin4D#11]
I am using Delphi 10.4.2 to build the demo.  I found that both demo doesn't return correct result:

Console demo fail at 
    Assert(casbin.enforce(['bob', 'user', 'delete']) = True);

VCL demo never always return Deny.

**Comment by hsluoyz** [comment]
@jkour

**Comment by jkour** [comment]
@ccy, I think some parts need rewriting TBH.

Hadnt noticed that one you are mentioning but I think the classes pass all the tests, don't they

**Comment by jkour** [comment]
What VCL demo? Do you mean the MainDemo which if FMX?

**Comment by jkour** [comment]
@ccy 
Hi there, 
All tests pass now. See the master branch eb13b61ea7f6c9e588253ec23030b61e081b160b
